---
title: "High-frequency econometrics: from realized volatility to realized drift"
subtitle: "DGPE PhD course at the Department of Mathematical Sciences, Aalborg University"
format:
    html: 
        toc: true
        number_sections: false
    typst: default
format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
---


## Course Description

The course is designed for PhD students who have an interest in the application of time series methods to financial data.
The analysis of tick-by-tick financial data has become a central topic in financial econometrics, driven by the increasing availability of such data. Compared with traditional time series, high-frequency data provide a substantial number of observations, which can yield richer information.

This course consists of two parts. The first part introduces the fundamental concepts of continuous-time econometrics, such as how to model log-prices, the infill asymptotic regime and how to estimate realized volatility. We also revise the concepts of Brownian motion and Poisson process. 

The second part will show the development of a recent research agenda which was devoted to the analysis of the drift component of the Itô semimartingale. The topics covered will be:

- Why drift is invisible in the classical case?
- Non classical model 1: drift bursts
- The economics of drift bursts
- Non classical model 2: frequency-dependent drift
- Back to the classical model: drift estimation
- Application: flash crashes, volatility explosions, volatility forecasting, momentum trading.


### Bibliography:

1. Laurent, S., and Shi, S. (2020). Volatility estimation and jump detection for drift–diffusion processes. Journal of Econometrics, 217(2), 259-290.

2. Christensen, K., Oomen, R., and Renò, R. (2022). The drift burst hypothesis. Journal of Econometrics, 227(2), 461–497.

3. Laurent, S., and Shi, S. (2022). Unit root test with high-frequency data. Econometric Theory, 38(1), 113-171.

4. Andersen, T. G., Li, Y., Todorov, V., and Zhou, B. (2023). Volatility measurement with pockets of extreme return persistence. Journal of Econometrics, 237(2), 105048.

5. Laurent, S., Renò, R., and Shi, S. (2024). Realized drift. Journal of Econometrics, 179, 105813.

6. Flora, M., Ferrara, G., and Renò, R. (2025). The Impact of COVID-19 on Italian Sovereign Bond Market Quality. Journal of Financial Services Research, 67, 55–71.

7. Flora, M., and Renò, R. (2025). V-Shapes. Journal of Banking and Finance, 179, 107521.

8. Kolokolov, A., Renò, R., and Zoi, P. (2025). BUMVU estimators. Journal of Econometrics, in press, 105942.

9. Bellia, M., Christensen, K., Kolokolov, A., Pelizzon, L., and Renò, R. (2025). Do Designated Market Makers Provide Liquidity During Extreme Downward Price Movements? Journal of Financial Markets, 76, 100988.

10. Benvenuti, F. and Renò, R. (2025). A seismometer for Itō semimartingales. Working Paper.


11. Aït-Sahalia, Y. and Jacod, J. [2014], High-frequency financial econometrics, Princeton University
Press.

12. Jacod, J. and Protter, P. E. [2012], Discretization of Processes, 2nd edn, Springer-Verlag, Berlin.

## Schedule

This course corresponds to 2 full days of teaching (12 hrs) in addition to readings and exam. The course will be held on the 26th and 27th March, both days for 3 hours in the morning and 3 hours in the afternoon.


## Instructors

- [Assistant professor Francesco Benvenuti](https://vbn.aau.dk/da/persons/fraben/), Aalborg University.

- [Associate professor Orimar Sauri](https://vbn.aau.dk/da/persons/osauri/), Aalborg University.

- [Professor Roberto Renò](https://roberto-reno.faculty.essec.edu/), ESSEC Business School.


## Prerequisites

Prerequisites: graduate level knowledge of statistics or econometrics; notions of probability theory and analysis.

## ECTS Credits

The course offers 2 ECTS credit points. A diploma for participation will be given to all attendees. 

In order to receive the 2 ECTS the students will have to submit a referee report of a paper assigned randomly, which deals with the topic of the course.

## Logistics

### Schedule

The course will be held on March 26–27, 2026. 

### Venue

The course will be held at AAU Innovate, Aalborg University, Aalborg, Denmark.

The building is located at Thomas Manns Vej 25, 9220 Aalborg East, Denmark.


<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2172.1507473874403!2d9.973768253554535!3d57.01472539086101!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464eccdbf9dfd6ed%3A0x727243796a71dd57!2sAAU%20Innovation!5e0!3m2!1sen!2sdk!4v1741339631309!5m2!1sen!2sdk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


### Registration

Please register for the course by filling in [this form](https://forms.office.com/e/VCaSDW31rS) no later than March 12, 2026.

### Fee

The course is free of charge for DGPE ([Danish Graduate Programme in Economics](https://econ.au.dk/dgpe)) members from AAU, AU, CBS, KU, and SDU, and for PhD students from Economics Departments at Nordic universities outside Denmark. For participants from other institutions, there is a standard fee of 100 EUR per day (200 EUR for the entire course).

Thanks to the DGPE support, lunch, tea and coffee throughout the course and one course dinner for all participants is included.

Costs associated with transportation and accommodation should be covered by the participants' home institutions. 


### Questions

For any questions regarding the course, please contact [Francesco Benvenuti](https://vbn.aau.dk/da/persons/fraben/), [fraben@math.aau.dk](mailto: fraben@math.aau.dk).

We look forward to welcoming you!
