---
title: "Department of Mathematical Sciences, Aalborg University"
---

This is the *offstage* page for the Department of Mathematical Sciences. You can find the official website [here](https://www.math.aau.dk/). This website is used for fast updates and hosting of events and research projects. It does not replace the official website, which maintains the official information.

## [Seminar Series](LSS.qmd)

The Department of Mathematical Sciences at Aalborg University hosts a monthly seminar series. You can find more information [here](LSS.qmd).

## [Earth Day and Climate Econometrics](https://climateaau.github.io)

The Department of Mathematical Sciences at Aalborg University is committed to the study of Climate Change and its impacts on society. It hosts the [Climate AAU Hub](https://climateaau.github.io), containing [Climate Econometrics Research Projects](https://climateaau.github.io/climateeconometrics.html) and the yearly [Earth Day Events](https://climateaau.github.io/earthday2024.html).

Furthermore, the Department is proud to host the upcoming 10th Conference on Econometric Models of Climate Change (EMCC-X) in August 20-21, 2026. More information about the conference at the official conference website [here](https://sites.google.com/view/emccconference) or the website for EMCC-X [here](https://climateaau.github.io/emcc-x).


## Previous Events

#### [Course on Resampling Techniques in Statistics and Data Science](Resampling-PhD.qmd)

The Department of Mathematical Sciences at Aalborg University hosted a PhD course on resampling techniques in statistics and data science. The course was on May 20th-21st, 2025. You can find more information [here](Resampling-PhD.qmd).

#### [PhD Course on Long Memory Processes](LM-PhD.qmd)

The Department of Mathematical Sciences at Aalborg University hosted a PhD course on long memory processes. The course was on November 26th-27th, 2024. You can find more information [here](LM-PhD.qmd).


#### [Long Memory Symposium](LMS.qmd)

The Long Memory Symposium is a collaboration between Aalborg University and Aarhus University. The last event in 2024 brought together researchers from across the world to discuss the latest advances in long memory processes and their applications. You can find more information [here](LMS.qmd).

#### [XV Anniversary of the Mathematics-Economics Program](XV.qmd)

The Mathematics-Economics Program at Aalborg University celebrated its 15th anniversary in 2024. The Department hosted an event to bring together students, alumni, faculty, and industry leaders to connect, reflect, and look ahead. You can find more information [here](XV.qmd).
